version: '3'
services:
  web:
    build:
        dockerfile: web.Dockerfile
    ports:
     - "8000:8000"
    environment:
      S3_ENDPOINT_URL: "http://host.docker.internal:9000"
      S3_ACCESS_KEY_ID: "custom_minioadmin"
      S3_SECRET: "custom_miniopassword"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - storage
  storage:
    build:
        dockerfile: storage.Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./tests/fixtures:/mount_dir"
    environment:
      MINIO_ROOT_USER: "custom_minioadmin"
      MINIO_ROOT_PASSWORD: "custom_miniopassword"
