services:
  webdav:
    build:
      context: .
      dockerfile: webdav.Dockerfile
    environment:
      - WEBDAV_USER=${WEBDAV_USER:-libression_user}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD:-libression_password}
      - NGINX_SECURE_LINK_KEY=${NGINX_SECURE_LINK_KEY:-libression_secret_key}
    ports:
      - "8443:443"
    volumes:
      - webdav_data:/var/www/webdav
    security_opt:
      - label:type:httpd_sys_content_t
      - label:level:s0:c1,c2
    cap_add:
      - NET_BIND_SERVICE
      - SETFCAP
    sysctls:
      - net.core.somaxconn=65535

volumes:
  webdav_data:
