[tool.poetry]
name = "libression"
version = "0.1.0"
description = "self-hosting media organiser"
authors = ["ern chow <chilledgeek@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
botocore = "^1.34"
fastapi = "^0.108"
uvicorn = "^0.25"
jinja2 = "^3.1"
python-multipart = "^0.0"
pyheif = "^0.7"
pillow = "^10.1"
boto3 = "^1.34"
mypy-boto3-s3 = "^1.34.14"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
mypy = "^1.8"
bandit = "^1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
